steps:
#STEP ONE : AUTHENTICATION TO DOCKER HUB 
- name: gcr.io/cloud-builders/docker
  id: 'Authentication'
  entrypoint: "bash"
  args: ["-c", "docker login --username=jonathan8231 --password=$$PASSWORD"]
  secretEnv: ["PASSWORD"]

# STEP TWO: BUILD IMAGE WTIH DOCKERFILE

- name: gcr.io/cloud-builders/docker
  id: 'Build docker image'
  args: ['build','-t', '$_IMAGE_NAME:$SHORT_SHA', '-f','$_DOCKERFILE_PATH', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', '$_IMAGE_NAME:$SHORT_SHA']  
# STEP FOUR: PREPARE TO DEPLOY
- name: gcr.io/cloud-builders/gke-deploy
  id: 'Prepare to deploy'
  args: 
  - 'prepare'
  - '--filename=$_K8S_YAML_PATH' 
  - '--image=$_IMAGE_NAME:$SHORT_SHA' 
  - '--app=$_K8S_APP_NAME' 
  - '--version=$SHORT_SHA' 
  - '--namespace=default' 
  - '--output=output' 
  - '--annotation=gcb-build-id=$BUILD_ID'
  
#STEP FIVE DEPLOYMENT
- name: gcr.io/cloud-builders/gke-deploy
  id: "Prepare for deployment"
  args: 
  - 'apply' 
  - '--filename=output/expanded' 
  - '--cluster=$_GKE_CLUSTER' 
  - '--location=$_GKE_LOCATION'
  
images:
  - $_IMAGE_NAME:$SHORT_SHA
substitutions:
   _DOCKERFILE_PATH: Dockerfile
   _IMAGE_NAME: jonathan8231/diabetes-webapp
   _GKE_CLUSTER: devfest-2020
   _GKE_LOCATION: europe-north1-a
   _K8S_YAML_PATH: gcloud/deployment.yaml
options:
     substitution_option: ALLOW_LOOSE

secrets:
- kmsKeyName: "projects/dev-fest-2020-294510/locations/global/keyRings/docker-hub-registry/cryptoKeys/dockerhub"
  secretEnv:
     PASSWORD: "CiQANy/koR0MQiWSjcaHRCcG7+tlPoY90ZlTuKX+afx5Nc2GwCMSNgD3ybiQ9C+l+HqoD2zwmWdNhQmkJdBntJmkKmCvWARJI5/cAB7LZGuaJ2eubhB1cphH0jA6dw=="
