apiVersion: v1
kind: Service
metadata:
  name: diabetes-webapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: diabetes-webapp
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: diabetes-webapp
